crm:
  image: genee/crm
  restart: always
  dns:
    - 172.17.0.1
  volumes:
    - .:/var/www
    - /etc/localtime:/etc/localtime:ro
    - ./files/root/var/lib/mysql:/var/lib/mysql
  container_name: crm
  environment:
    - VIRTUAL_HOST=crm.reserva.genee.cn,crm.reserva.genee.in
